name: Sanity test with YugabyteDB preview build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_BOT_USERNAME }}
          password: ${{ secrets.QUAY_BOT_TOKEN }}
      - name: Pull docker image
        env:
          YB_DOCKER_IMAGE: ${{ secrets.YB_DOCKER_IMAGE_PREVIEW }}
        run: docker pull $YB_DOCKER_IMAGE
      - name: Sanity Test that code compiles and tests pass.
        env:
          YB_DOCKER_IMAGE: ${{ secrets.YB_DOCKER_IMAGE_PREVIEW }}
        run: mvn clean test -Dtest=!YugabyteDBColocatedTablesTest#shouldWorkWithMixOfColocatedAndNonColocatedTables
      - name: Flaky test YugabyteDBColocatedTablesTest#shouldWorkWithMixOfColocatedAndNonColocatedTables
        env:
          YB_DOCKER_IMAGE: ${{ secrets.YB_DOCKER_IMAGE_PREVIEW }}
        run: mvn clean test -Dtest=YugabyteDBColocatedTablesTest#shouldWorkWithMixOfColocatedAndNonColocatedTables
